### ISSUE TITLE
Confusing exception during metric creation.

### ISSUE THREAD

**Issue by InKolev** [prometheus-net/prometheus-net#100]
Hi, I receive the following exception when trying to execute this piece of code:

**Code:**
```
            var metricServer = new MetricPusher(endpoint: "http://tralala:9091/metrics", job: "jobname");
            metricServer.Start();

            var currentDateEDT = DateTime.UtcNow.AddHours(-4);
            var currentHourEDT = currentDateEDT.Hour;

            var gaugeEDT = Metrics.CreateGauge("currentHour ", "edt timezone");
            gaugeEDT.Set(currentHourEDT);
            gaugeEDT.Publish();
```

**Exception:**
```
Metric name 'currentHour ' does not match regex '^[a-zA-Z_:][a-zA-Z0-9_:]*$'.: ArgumentException
   at Prometheus.Advanced.Collector`1..ctor(String name, String help, String[] labelNames, Boolean suppressInitialValue)
   at Prometheus.Advanced.MetricFactory.CreateGauge(String name, String help, GaugeConfiguration configuration)
   at Serverless.CurrentTimeReporter.Function.FunctionHandler(ILambdaContext context)
```

Can someone explain why I receive this exception when the metric name perfectly matches the regex pattern?

**Comment by sandersaares** [comment]
There is a space character at the end if your metric name. Space is not a valid character in metric names.

**Comment by InKolev** [comment]
Ah, I guess working late at night is not very productive.
Thanks for the tip, mate.

I am closing the issue.
