### ISSUE TITLE
OperationCanceledException thrown by ASP.NET Core exporter

### ISSUE THREAD

**Issue by NichUK** [prometheus-net/prometheus-net#220]
I just upgraded a working .NET Core 3.0 project to 3.1, and all the dependencies and libraries to latest stable version, and I am now regularly getting the exception shown below.
If I un-map the Metrics endpoint, it goes away, so I'm pretty certain it's something to do with prometheus-net, but I haven't been able to determine more than that, so far.
It doesn't seem to happen on every metrics access, just occasionally, and often two together, as shown.
I'd be grateful for any ideas on how to proceed to both determine why this is happening, and obviously also to sort it out.

`[11:27:12.1722] fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLVV0C8BHLEK", Request id "0HLVV0C8BHLEK:00000002": An unhandled exception was thrown by the application.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Prometheus.TextSerializer.WriteFamilyDeclarationAsync(Byte[][] headerLines, CancellationToken cancel)
   at Prometheus.Collector``1.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.CollectorRegistry.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.MetricServerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication``1 application)
[11:27:12.1743] fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLVV0C8BHLEM", Request id "0HLVV0C8BHLEM:00000001": An unhandled exception was thrown by the application.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Prometheus.TextSerializer.WriteFamilyDeclarationAsync(Byte[][] headerLines, CancellationToken cancel)
   at Prometheus.Collector``1.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.CollectorRegistry.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.MetricServerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication``1 application)
`

**Comment by NichUK** [comment]
I managed to fix this issue by downgrading prometheus-net:

    <PackageReference Include="prometheus-net.AspNetCore" Version="3.4.0" />
    <PackageReference Include="prometheus-net.DotNetRuntime" Version="3.3.0" />

The exceptions no longer appear.

**Comment by cmannix** [comment]
Hi - I suspect this is happening due to #189 which was included in the latest release, hence why downgrading fixed things. Not sure what the actual issue is yet (or indeed if it's an issue with prometheus-net or elsewhere) - will try and dig in further.

**Comment by NichUK** [comment]
I don't have anything shareable immediately, but if I get a chance over the next couple of days, I'll try and reproduce in a clean project.

**Comment by sandersaares** [comment]
This exception means that the HTTP request was aborted by the HTTP client.

This is normal in various situations like:

1. Hitting refresh a lot in the browser (new requests will typically cancel old ones).
1. The scrape taking a long time so there is a timeout (unusual, except if you have some long-running pre-scrape processes running every time).

Might you be encountering either of these situations?

**Comment by NichUK** [comment]
@sandersaares, I shouldn't be encoutering either of those situations. 
It's a bog-standard implementation using prometheus-net to monitor the .net state for an application.
In addition, the problem was completely solved by downgrading (100% no errors since), which implies that the issue is definitely in the library, but could, I suppose be something to do with situation 2 if changes to the library caused a significant slow-down in scrape time?

**Comment by sandersaares** [comment]
> I suppose be something to do with situation 2 if changes to the library caused a significant slow-down in scrape time?

The previous version of the library processed even aborted requests to the end. The difference is not that requests did not get aborted in the past, the difference is that now this is visible.

The main place where I have seen users cause scrape timeouts is by executing a lot of time-consuming logic via `AddBeforeCollectCallback`. Do you use these callbacks?

**Comment by NichUK** [comment]
No, I'm not using any callbacks.

**Comment by sandersaares** [comment]
Interesting. I have no other ideas at the moment. Let's leave this open and hope someone can provide a code sample that can be used to reproduce it for investigation.

**Comment by NichUK** [comment]
Yes. I'm sorry, we're rushing to hit a deadline, so I haven't had any time to try and build a repro.

**Comment by sandersaares** [comment]
There's really no benefit to logging this, so I will change the code to swallow the exception and pretend nothing happened. If this exception happens, ASP.NET Core is in abort mode already anyway, so it doesn't benefit from the exception (maybe some middleware might, in theory, but unlikely in practice).

**Comment by sandersaares** [comment]
This is now available in preview NuGet package version 3.6.0-pre-000129-bd91778. Please give it a try. If no problems are reported within a few days, I will publish this build as stable package.
