### ISSUE TITLE
Exception in HttpListener server

### ISSUE THREAD

**Issue by sandersaares** [prometheus-net/prometheus-net#241]
```
Error in MetricServer: System.Net.HttpListenerException (1229): An operation was attempted on a nonexistent network connection.
   at System.Net.HttpResponseStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.Net.HttpResponseStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__61_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Prometheus.TextSerializer.WriteFamilyDeclarationAsync(Byte[][] headerLines, CancellationToken cancel)
   at Prometheus.Collector`1.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.CollectorRegistry.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.MetricServer.<>c__DisplayClass3_1.<<StartServer>b__1>d.MoveNext()
The thread 0x4bb4 has exited with code 0 (0x0).
```

**Comment by sandersaares** [comment]
I suppose this can be normal in some scenarios where the connection is closed? Does not happen a lot, will classify this as "HttpListener being weird".
