### ISSUE TITLE
Error during runtime: Unable to write data to the transport connection: Broken pipe.

### ISSUE THREAD

**Issue by alphaWizard** [prometheus-net/prometheus-net#254]
I am using custom metrics, in the following way.
```
failureInteractingHC = Metrics.CreateCounter("clusterconnect_hc_interaction_failed", "The cluster connect agent failed to interact with HC.");
failureInteractingNotificationService = Metrics.CreateCounter("clusterconnect_notification_service_interaction_failed", "The cluster connect agent failed to interact with notification service.");

await CustomMetrics.failureInteractingHC.CountExceptionsAsync(async() => await listener.OpenAsync(shuttingDown.Token));
var hybridConnectionStream = await CustomMetrics.failureInteractingHC.CountExceptionsAsync(async () => await listener.AcceptConnectionAsync());
```

**Error in MetricsServer: System.Net.HttpListenerException (0x80131620): Unable to write data to the transport connection: Broken pipe.**
   at System.Net.HttpResponseStream.EndWriteCore(IAsyncResult asyncResult)
   at System.Net.HttpResponseStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__61_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Prometheus.TextSerializer.WriteFamilyDeclarationAsync(Byte[][] headerLines, CancellationToken cancel)
   at Prometheus.Collector`1.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.CollectorRegistry.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.MetricServer.<>c__DisplayClass3_1.<<StartServer>b__1>d.MoveNext()

**Comment by sandersaares** [comment]
This sounds like some connectivity error between your app and Prometheus.

If you can post a sample app that can reliably reproduce this issue, I can try investigating further.
