### ISSUE TITLE
HttpClientMetrics register their HttpMessageHandlers as Scoped causing exceptions upon reuse.

### ISSUE THREAD

**Issue by EraYaN** [prometheus-net/prometheus-net#301]
This seems to cause exceptions like 

```
System.InvalidOperationException: The 'InnerHandler' property must be null. 'DelegatingHandler' instances provided to 'HttpMessageHandlerBuilder' must not be reused or cached.
Handler: 'Prometheus.HttpClientMetrics.HttpClientRequestDurationHandler'
   at Microsoft.Extensions.Http.HttpMessageHandlerBuilder.CreateHandlerPipeline(HttpMessageHandler primaryHandler, IEnumerable`1 additionalHandlers)
   at Microsoft.Extensions.Http.DefaultHttpMessageHandlerBuilder.Build()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandlerEntry(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.<>c__DisplayClass14_0.<.ctor>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateHandler(String name)
   at Microsoft.Extensions.Http.DefaultHttpClientFactory.CreateClient(String name)
   at Grpc.Net.ClientFactory.Internal.DefaultGrpcClientFactory.CreateClient[TClient](String name) in /_/src/Grpc.Net.ClientFactory/Internal/DefaultGrpcClientFactory.cs:line 53
   at Microsoft.Extensions.DependencyInjection.GrpcClientServiceExtensions.<>c__DisplayClass7_0`1.<AddGrpcHttpClient>b__1(IServiceProvider s) in /_/src/Grpc.Net.ClientFactory/GrpcClientServiceExtensions.cs:line 353
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitDisposeCache(ServiceCallSite transientCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method223(Closure , IServiceProvider , Object[] )
   at Grpc.AspNetCore.Server.Internal.DefaultGrpcServiceActivator`1.Create(IServiceProvider serviceProvider) in /_/src/Grpc.AspNetCore.Server/Internal/DefaultGrpcServiceActivator.cs:line 42
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext) in /_/src/Shared/Server/UnaryServerMethodInvoker.cs:line 71
   at Grpc.Shared.Server.UnaryServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest resolvedRequest, ServerCallContext resolvedContext) in /_/src/Shared/Server/UnaryServerMethodInvoker.cs:line 78
```

When having more than one child request to gRPC services. They are registered here https://github.com/prometheus-net/prometheus-net/blob/master/Prometheus.AspNetCore/HttpClientMetricsExtensions.cs#L30-L32

For some of my custom handlers making them Transient fixes the problem, but it might just be that the HttpClients for Grpc mess with things.

**Comment by sandersaares** [comment]
The handler registration mechanism has changed recently as part of unrelated changes and I suspect this might now be fixed. If you have a moment, please try to upgrading to the latest prerelease version of 4.3.0.

**Comment by EraYaN** [comment]
For now I can't yet try it since we depend on some currently open PRs, from me (HttpStatusCode in Client metrics) and from @Sverdel (Grpc Request Duration Histograms). I'll give it a try as soon as I will move back to an upstream version. If I have some time I'll try to rebase mine to current master.
