### ISSUE TITLE
Metrics Server Crash due errror while write to Output Stream

### ISSUE THREAD

**Issue by kaiwie** [prometheus-net/prometheus-net#356]
I found some exceptions in my tracelog wich comes from the prometheus-net implementation. 
This Results in an restart of the metrics server so it seems robust for me and only a few metrics may lost.

I would prefer to handle the Error to avoid the crash and also avoid the exception logging. Maybe it is  enought to check if the stream ist writeable.

`        public async Task WriteMetricAsync(byte[] identifier, double value, CancellationToken cancel)
        {
            **if (_stream.Value.CanWrite)
            {
                return;
            }**

            await _stream.Value.WriteAsync(identifier, 0, identifier.Length, cancel);
            await _stream.Value.WriteAsync(Space, 0, Space.Length, cancel);

            var valueAsString = value.ToString(CultureInfo.InvariantCulture);

            var numBytes = PrometheusConstants.ExportEncoding
                .GetBytes(valueAsString, 0, valueAsString.Length, _stringBytesBuffer, 0);

            await _stream.Value.WriteAsync(_stringBytesBuffer, 0, numBytes, cancel);
            await _stream.Value.WriteAsync(NewLine, 0, NewLine.Length, cancel);
        }`
 
StackTrace:

`Error in MetricServer: System.Net.HttpListenerException (0x80004005): An operation was attempted on a nonexistent network connection
   at System.Net.HttpResponseStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Prometheus.TextSerializer.<WriteMetricAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Prometheus.Collector`1.<CollectAndSerializeAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Prometheus.CollectorRegistry.<CollectAndSerializeAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Prometheus.MetricServer.<>c__DisplayClass7_1.<<StartServer>b__1>d.MoveNext()`

**Comment by werebear73** [comment]
I have been running into this as well.  

```Error in MetricServer: System.Net.HttpListenerException (0x80131620): Unable to write data to the transport connection: Broken pipe.
   at System.Net.HttpResponseStream.EndWriteCore(IAsyncResult asyncResult)
   at System.Net.HttpResponseStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__58_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Prometheus.TextSerializer.WriteFamilyDeclarationAsync(Byte[][] headerLines, CancellationToken cancel)
   at Prometheus.Collector`1.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.CollectorRegistry.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.MetricServer.<>c__DisplayClass7_1.<<StartServer>b__1>d.MoveNext()
Error in MetricServer: System.Net.HttpListenerException (0x80131620): Unable to write data to the transport connection: Broken pipe.
   at System.Net.HttpResponseStream.InternalWrite(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.HttpResponseStream.BeginWriteCore(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback cback, Object state)
   at System.Net.HttpResponseStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback, Object state)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__58_0(Stream stream, ReadWriteParameters args, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrim[TInstance,TArgs](TInstance thisRef, TArgs args, Func`5 beginMethod, Func`3 endMethod)
   at System.IO.Stream.BeginEndWriteAsync(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Prometheus.TextSerializer.WriteFamilyDeclarationAsync(Byte[][] headerLines, CancellationToken cancel)
   at Prometheus.Collector`1.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.CollectorRegistry.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.MetricServer.<>c__DisplayClass7_1.<<StartServer>b__1>d.MoveNext()```

I am still trying to find the line of code causing the error.

**Comment by craigbryson** [comment]
Running into this too - did you have much luck finding the cause @werebear73 ?

**Comment by werebear73** [comment]
I'm still see this.  Anyone else still having this issue?

**Comment by sandersaares** [comment]
Such exceptions are normal - it just means whatever was requesting metrics from the server terminated the connection before it received the metrics (maybe due to network fault, maybe due to something else). In general, the code will log and ignore such exceptions.

You mention a service restart in the original post, which is unexpected - if you are seeing restarts related to this, it might be sign of some bigger problem.

You can alternatively try `KestrelMetricServer` which uses a more modern HTTP stack and may perhaps have better behavior due to this.
