### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/net/eth0/tx_queue_len'

### ISSUE THREAD

**Issue by digitalsigi** [prometheus-net/prometheus-net#370]
THy for your excellent work. On my test system everything went fine, but on production system I face following error:
```
[16:17:38 ERR] An unhandled exception has occurred while executing the request.
System.IO.DirectoryNotFoundException: Could not find a part of the path '/sys/class/net/eth0/tx_queue_len'.
   at Interop.CheckIo(Error error, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPInterfaceStatistics..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetIPStatistics()
   at Prometheus.SystemMetrics.Collectors.NetworkCollector.UpdateMetrics()
   at Prometheus.CollectorRegistry.CollectAndSerializeAsync(IMetricsSerializer serializer, CancellationToken cancel)
   at Prometheus.MetricServerMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
The machine does not have an eth0 interface but a couple of others. 
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: venet0: <BROADCAST,POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/void
3: br-45685494836c: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default
    link/ether 02:42:c2:d5:de:f5 brd ff:ff:ff:ff:ff:ff
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 02:42:3c:66:3d:26 brd ff:ff:ff:ff:ff:ff
8: veth50f3913@if7: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-45685494836c state UP mode DEFAULT group default
    link/ether fe:5d:c4:3a:db:87 brd ff:ff:ff:ff:ff:ff link-netnsid 0
26: vethb73d9f8@if25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-45685494836c state UP mode DEFAULT group default
    link/ether 82:7d:90:6a:62:2a brd ff:ff:ff:ff:ff:ff link-netnsid 3
30: veth4aca806@if29: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-45685494836c state UP mode DEFAULT group default
    link/ether aa:1b:8d:5d:5b:87 brd ff:ff:ff:ff:ff:ff link-netnsid 1
34: veth5b4c06d@if33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-45685494836c state UP mode DEFAULT group default
    link/ether de:e3:ca:69:ef:63 brd ff:ff:ff:ff:ff:ff link-netnsid 2
42: veth8120938@if41: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-45685494836c state UP mode DEFAULT group default
    link/ether 02:57:13:c7:0e:9e brd ff:ff:ff:ff:ff:ff link-netnsid 6
44: vethaaf9f90@if43: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-45685494836c state UP mode DEFAULT group default
    link/ether 46:5b:70:82:e7:65 brd ff:ff:ff:ff:ff:ff link-netnsid 7
46: vethfc46cee@if45: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-45685494836c state UP mode DEFAULT group default
    link/ether aa:a1:26:82:e8:3d brd ff:ff:ff:ff:ff:ff link-netnsid 8
56: veth37831de@if55: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-45685494836c state UP mode DEFAULT group default
    link/ether 6a:f1:16:44:5e:d6 brd ff:ff:ff:ff:ff:ff link-netnsid 9
60: veth9c60d28@if59: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-45685494836c state UP mode DEFAULT group default
    link/ether 06:60:32:ff:3b:31 brd ff:ff:ff:ff:ff:ff link-netnsid 4
````
How to overcome this?

**Comment by sandersaares** [comment]
From the stack trace, this seems like an issue with the https://github.com/Daniel15/prometheus-net.SystemMetrics community-contributed library, not the prometheus-net library itself.
