### ISSUE TITLE
No 500 response status metrics reported

### ISSUE THREAD

**Issue by AceHack** [prometheus-net/prometheus-net#483]
I only see request metrics. What do I need to do to enable request metrics?  I made every return, returning 500 errors, but I only see 200 requests, not 500 responses.

```
        public static void Main(string[] args)
        {
            var builder = WebApplication.CreateBuilder(args);

            // Add services to the container.  

            builder.Services.AddControllers();
            // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle  
            builder.Services.AddEndpointsApiExplorer();
            builder.Services.AddSwaggerGen();
            builder.Services.AddSingleton<CBP>();
            builder.Services.AddHttpClient("PolyTest", client =>
            {
                client.BaseAddress = new Uri("https://localhost:5002");
            }).AddPolicyHandler((sp, req) =>
            {
                var cbp = sp.GetRequiredService<CBP>();
                return cbp.Policy;
            });

            builder.Services.UseHttpClientMetrics();
            var app = builder.Build();

            // Configure the HTTP request pipeline.  
            if (app.Environment.IsDevelopment())
            {
                app.UseSwagger();
                app.UseSwaggerUI();
            }

            app.UseHttpMetrics();

            app.UseHttpsRedirection();

            app.UseAuthorization();

            app.UseMetricServer();

            app.MapControllers();

            app.Run();
        }

    }
```

```
# HELP http_request_duration_seconds The duration of HTTP requests processed by an ASP.NET Core application.
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_sum{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast"} 5.6528450999999995
http_request_duration_seconds_count{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast"} 5
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="0.001"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="0.002"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="0.004"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="0.008"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="0.016"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="0.032"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="0.064"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="0.128"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="0.256"} 3
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="0.512"} 4
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="1.024"} 4
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="2.048"} 4
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="4.096"} 4
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="8.192"} 5
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="16.384"} 5
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="32.768"} 5
http_request_duration_seconds_bucket{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast",le="+Inf"} 5
# HELP http_requests_received_total Provides the count of HTTP requests that have been processed by the ASP.NET Core pipeline.
# TYPE http_requests_received_total counter
http_requests_received_total{code="200",method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast"} 5
# HELP http_requests_in_progress The number of requests currently in progress in the ASP.NET Core pipeline. One series without controller/action label values counts all in-progress requests, with separate series existing for each controller-action pair.
# TYPE http_requests_in_progress gauge
http_requests_in_progress{method="GET",controller="WeatherForecast",action="Get",endpoint="WeatherForecast"} 0
# HELP httpclient_requests_in_progress Number of requests currently being executed by an HttpClient that have not yet received response headers. Value is decremented once response headers are received.
# TYPE httpclient_requests_in_progress gauge
httpclient_requests_in_progress{method="GET",host="localhost",client="PolyTest",code=""} 0
# HELP httpclient_requests_sent_total Count of HTTP requests that have been completed by an HttpClient.
# TYPE httpclient_requests_sent_total counter
httpclient_requests_sent_total{method="GET",host="localhost",client="PolyTest",code=""} 1
# HELP httpclient_request_duration_seconds Duration histogram of HTTP requests performed by an HttpClient.
# TYPE httpclient_request_duration_seconds histogram
httpclient_request_duration_seconds_sum{method="GET",host="localhost",client="PolyTest",code=""} 4.141892
httpclient_request_duration_seconds_count{method="GET",host="localhost",client="PolyTest",code=""} 1
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="0.001"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="0.002"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="0.004"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="0.008"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="0.016"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="0.032"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="0.064"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="0.128"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="0.256"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="0.512"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="1.024"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="2.048"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="4.096"} 0
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="8.192"} 1
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="16.384"} 1
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="32.768"} 1
httpclient_request_duration_seconds_bucket{method="GET",host="localhost",client="PolyTest",code="",le="+Inf"} 1
# HELP httpclient_response_duration_seconds Duration histogram of HTTP requests performed by an HttpClient, measuring the duration until the HTTP response finished being processed.
# TYPE httpclient_response_duration_seconds histogram
# HELP dotnet_collection_count_total GC collection count
# TYPE dotnet_collection_count_total counter
dotnet_collection_count_total{generation="0"} 0
dotnet_collection_count_total{generation="1"} 0
dotnet_collection_count_total{generation="2"} 0
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds.
# TYPE process_start_time_seconds gauge
process_start_time_seconds 1728335943.4304476
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds.
# TYPE process_cpu_seconds_total counter
process_cpu_seconds_total 2.78125
# HELP process_virtual_memory_bytes Virtual memory size in bytes.
# TYPE process_virtual_memory_bytes gauge
process_virtual_memory_bytes 2481053573120
# HELP process_working_set_bytes Process working set
# TYPE process_working_set_bytes gauge
process_working_set_bytes 124579840
# HELP process_private_memory_bytes Process private memory size
# TYPE process_private_memory_bytes gauge
process_private_memory_bytes 90456064
# HELP process_open_handles Number of open handles
# TYPE process_open_handles gauge
process_open_handles 805
# HELP process_num_threads Total number of threads
# TYPE process_num_threads gauge
process_num_threads 51
# HELP dotnet_total_memory_bytes Total known allocated memory
# TYPE dotnet_total_memory_bytes gauge
dotnet_total_memory_bytes 16166000
# HELP prometheus_net_metric_families Number of metric families currently registered.
# TYPE prometheus_net_metric_families gauge
prometheus_net_metric_families{metric_type="counter"} 6
prometheus_net_metric_families{metric_type="gauge"} 20
prometheus_net_metric_families{metric_type="summary"} 0
prometheus_net_metric_families{metric_type="histogram"} 3
# HELP prometheus_net_metric_instances Number of metric instances currently registered across all metric families.
# TYPE prometheus_net_metric_instances gauge
prometheus_net_metric_instances{metric_type="counter"} 7
prometheus_net_metric_instances{metric_type="gauge"} 29
prometheus_net_metric_instances{metric_type="summary"} 0
prometheus_net_metric_instances{metric_type="histogram"} 2
# HELP prometheus_net_metric_timeseries Number of metric timeseries currently generated from all metric instances.
# TYPE prometheus_net_metric_timeseries gauge
prometheus_net_metric_timeseries{metric_type="counter"} 7
prometheus_net_metric_timeseries{metric_type="gauge"} 29
prometheus_net_metric_timeseries{metric_type="summary"} 0
prometheus_net_metric_timeseries{metric_type="histogram"} 38
# HELP prometheus_net_exemplars_recorded_total Number of exemplars that were accepted into in-memory storage in the prometheus-net SDK.
# TYPE prometheus_net_exemplars_recorded_total counter
prometheus_net_exemplars_recorded_total 0
# HELP prometheus_net_eventcounteradapter_sources_connected_total Number of event sources that are currently connected to the adapter.
# TYPE prometheus_net_eventcounteradapter_sources_connected_total gauge
prometheus_net_eventcounteradapter_sources_connected_total 7
# HELP prometheus_net_meteradapter_instruments_connected Number of instruments that are currently connected to the adapter.
# TYPE prometheus_net_meteradapter_instruments_connected gauge
prometheus_net_meteradapter_instruments_connected 23
# HELP system_net_nameresolution_dns_lookups_requested DNS Lookups Requested
# TYPE system_net_nameresolution_dns_lookups_requested gauge
system_net_nameresolution_dns_lookups_requested 3
# HELP system_net_nameresolution_current_dns_lookups Current DNS Lookups
# TYPE system_net_nameresolution_current_dns_lookups gauge
system_net_nameresolution_current_dns_lookups 0
# HELP system_net_nameresolution_dns_lookups_duration (ms) Average DNS Lookup Duration
# TYPE system_net_nameresolution_dns_lookups_duration gauge
system_net_nameresolution_dns_lookups_duration 0
# HELP system_runtime_cpu_usage (%) CPU Usage
# TYPE system_runtime_cpu_usage gauge
system_runtime_cpu_usage 0.6264682850430697
# HELP system_runtime_working_set (MB) Working Set
# TYPE system_runtime_working_set gauge
system_runtime_working_set 123.564032
# HELP system_runtime_gc_heap_size (MB) GC Heap Size
# TYPE system_runtime_gc_heap_size gauge
system_runtime_gc_heap_size 16.182448
# HELP system_runtime_gen_0_gc_count_total Gen 0 GC Count
# TYPE system_runtime_gen_0_gc_count_total counter
system_runtime_gen_0_gc_count_total 0
# HELP system_runtime_gen_1_gc_count_total Gen 1 GC Count
# TYPE system_runtime_gen_1_gc_count_total counter
system_runtime_gen_1_gc_count_total 0
# HELP system_runtime_gen_2_gc_count_total Gen 2 GC Count
# TYPE system_runtime_gen_2_gc_count_total counter
system_runtime_gen_2_gc_count_total 0
# HELP system_runtime_gen_0_gc_budget (MB) Gen 0 GC Budget
# TYPE system_runtime_gen_0_gc_budget gauge
system_runtime_gen_0_gc_budget 314
# HELP system_runtime_threadpool_thread_count ThreadPool Thread Count
# TYPE system_runtime_threadpool_thread_count gauge
system_runtime_threadpool_thread_count 6
# HELP system_runtime_monitor_lock_contention_count_total Monitor Lock Contention Count
# TYPE system_runtime_monitor_lock_contention_count_total counter
system_runtime_monitor_lock_contention_count_total 0
# HELP system_runtime_threadpool_queue_length ThreadPool Queue Length
# TYPE system_runtime_threadpool_queue_length gauge
system_runtime_threadpool_queue_length 0
# HELP system_runtime_threadpool_completed_items_count_total ThreadPool Completed Work Item Count
# TYPE system_runtime_threadpool_completed_items_count_total counter
system_runtime_threadpool_completed_items_count_total 13
# HELP system_runtime_alloc_total (B) Allocation Rate
# TYPE system_runtime_alloc_total counter
system_runtime_alloc_total 283360
# HELP system_runtime_active_timer_count Number of Active Timers
# TYPE system_runtime_active_timer_count gauge
system_runtime_active_timer_count 4
# HELP system_runtime_gc_fragmentation (%) GC Fragmentation
# TYPE system_runtime_gc_fragmentation gauge
system_runtime_gc_fragmentation 0
# HELP system_runtime_gc_committed (MB) GC Committed Bytes
# TYPE system_runtime_gc_committed gauge
system_runtime_gc_committed 0
# HELP system_runtime_exception_count_total Exception Count
# TYPE system_runtime_exception_count_total counter
system_runtime_exception_count_total 0
# HELP system_runtime_time_in_gc (%) % Time in GC since last GC
# TYPE system_runtime_time_in_gc gauge
system_runtime_time_in_gc 0
# HELP system_runtime_total_pause_time_by_gc_total (ms) Time paused by GC
# TYPE system_runtime_total_pause_time_by_gc_total counter
system_runtime_total_pause_time_by_gc_total 0
# HELP system_runtime_gen_0_size (B) Gen 0 Size
# TYPE system_runtime_gen_0_size gauge
system_runtime_gen_0_size 0
# HELP system_runtime_gen_1_size (B) Gen 1 Size
# TYPE system_runtime_gen_1_size gauge
system_runtime_gen_1_size 0
# HELP system_runtime_gen_2_size (B) Gen 2 Size
# TYPE system_runtime_gen_2_size gauge
system_runtime_gen_2_size 0
# HELP system_runtime_loh_size (B) LOH Size
# TYPE system_runtime_loh_size gauge
system_runtime_loh_size 0
# HELP system_runtime_poh_size (B) POH (Pinned Object Heap) Size
# TYPE system_runtime_poh_size gauge
system_runtime_poh_size 0
# HELP system_runtime_assembly_count Number of Assemblies Loaded
# TYPE system_runtime_assembly_count gauge
system_runtime_assembly_count 147
# HELP system_runtime_il_bytes_jitted (B) IL Bytes Jitted
# TYPE system_runtime_il_bytes_jitted gauge
system_runtime_il_bytes_jitted 506645
# HELP system_runtime_methods_jitted_count Number of Methods Jitted
# TYPE system_runtime_methods_jitted_count gauge
system_runtime_methods_jitted_count 6502
# HELP system_runtime_time_in_jit_total (ms) Time spent in JIT
# TYPE system_runtime_time_in_jit_total counter
system_runtime_time_in_jit_total 112.61119999999983
```

**Comment by AceHack** [comment]
I had to add this middleware for it to work. Is this expected?

```
            app.Use(async (context, next) =>
            {
                try
                {
                    await next(context).ConfigureAwait(false);
                }
                catch
                {
                    context.Response.StatusCode = 500;
                    throw;
                }
            });
```

**Comment by andrisak** [comment]
Here is a minimal repro for this issue. Tested on `dotnet 9.0.100` using `prometheus-net.AspNetCore 8.2.1`.

```csharp
using Prometheus;

var builder = WebApplication.CreateBuilder(args);

var app = builder.Build();
app.UseHttpMetrics();
app.MapMetrics();
app.MapGet("/error", () => { throw new Exception("Error"); });

app.Run();
```

Doing

```sh
curl localhost:5000/error
```

results in this log with the status code 500:

```log
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HN9HALNGTABN", Request id "0HN9HALNGTABN:00000001": An unhandled exception was thrown by the application.
      System.Exception: Error
         at Program.<>c.<<Main>$>b__0_1() in /Users/***/Program.cs:line 21
         at lambda_method1(Closure, Object, HttpContext)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
         at Program.<>c.<<<Main>$>b__0_0>d.MoveNext() in /Users/andrisak/lab/prom-500/Program.cs:line 12
      --- End of stack trace from previous location ---
         at Prometheus.HttpMetrics.HttpRequestDurationMiddleware.Invoke(HttpContext context)
         at Prometheus.HttpMetrics.HttpRequestCountMiddleware.Invoke(HttpContext context)
         at Prometheus.HttpMetrics.HttpInProgressMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 GET http://localhost:5000/error - 500 0 - 37.5532ms
```
The metrics

```sh
curl localhost:5000/metrics
```

record the request with a 200 status code:

```sh
# HELP http_request_duration_seconds The duration of HTTP requests processed by an ASP.NET Core application.
# TYPE http_request_duration_seconds histogram
http_request_duration_seconds_sum{code="200",method="GET",controller="",action="",endpoint="/error"} 0.0017603
http_request_duration_seconds_count{code="200",method="GET",controller="",action="",endpoint="/error"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="0.001"} 0
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="0.002"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="0.004"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="0.008"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="0.016"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="0.032"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="0.064"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="0.128"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="0.256"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="0.512"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="1.024"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="2.048"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="4.096"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="8.192"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="16.384"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="32.768"} 1
http_request_duration_seconds_bucket{code="200",method="GET",controller="",action="",endpoint="/error",le="+Inf"} 1
```

Adding the middleware suggested by @AceHack after `app.UseHttpMetrics();` makes the request get recorded with a 500 status code, as expected.
